apiVersion: 1

datasources:
  - name: InfluxDB
    type: influxdb
    access: proxy
    url: http://influxdb:8086
    jsonData:
      version: Flux
      organization: iot_monitoring
      defaultBucket: sensor_data
      tlsSkipVerify: true
    secureJsonData:
      token: my-super-secret-admin-token-change-me
    editable: true
    isDefault: true
